name: Codeception Tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        operating-system: [ ubuntu-latest ]
        php-versions: [ '5.6' ]
        wp-versions: [ '5.6' ]

    name: WordPress ${{ matrix.wp-versions }} using PHP ${{ matrix.php-versions }} and tested on ${{ matrix.operating-system }}

    services:
      mariadb:
        image: mariadb:10.5
        ports:
          - 3306
        env:
          MYSQL_USER: root
          MYSQL_PASSWORD: root
          MYSQL_DATABASE: test
          MYSQL_ROOT_PASSWORD: root
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3

    steps:
      - name: Prepare
        run: sudo chown -R $USER:$USER ${{ github.workspace }}

      - name: Verify MariaDB connection
        env:
          PORT: ${{ job.services.mariadb.ports[3306] }}
        run: |
          while ! mysqladmin ping -h"127.0.0.1" -P"$PORT" --silent; do
            sleep 1
          done

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, pdo, pdo_mysql, intl, zip, json, xdebug
          ini-values: post_max_size=256M
          tools: pecl
          coverage: true

      - name: Check PHP Version
        run: php -v

      - name: Check PHP Extensions
        run: php -m

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install composer dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install --prefer-dist --no-progress --no-suggest
