name: Codeception Tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

env:
  TZ: UTC

jobs:
  test:

    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        operating-system: [ ubuntu-latest ]
        php-versions: [ '5.6' ]
        wp-versions: [ '5.6' ]

    name: WordPress ${{ matrix.wp-versions }} using PHP ${{ matrix.php-versions }} and tested on ${{ matrix.operating-system }}

    env:
      SELENIUM_HOST: http://selenium:4444/wd/hub

    services:
      selenium:
        image: selenium/standalone-chrome
        # options: --health-cmd "curl http://selenium:4444" --health-interval=5s
        ports:
          - 4444:4444

    steps:
      - name: Prepare
        run: sudo chown -R $USER:$USER ${{ github.workspace }}

      - name: Shutdown Ubuntu MySQL
        run: sudo service mysql stop

      - name: Set up MariaDB
        uses: getong/mariadb-action@v1.1
        with:
          character set server: 'utf8'
          collation server: 'utf8_general_ci'
          mariadb version: '10.5.8'
          mysql root password: 'root'
          mysql user: 'root'
          mysql password: 'root'

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, pdo, pdo_mysql, intl, zip, json, xdebug
          ini-values: post_max_size=256M
          tools: pecl
          coverage: true

      - name: Install Apache
        run: sudo apt-get install apache2

      - name: Check PHP Version
        run: php -v

      - name: Check PHP Extensions
        run: php -m

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install composer dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Build WordPress ${{ matrix.wp-versions }}
        run: ./init ${{ matrix.wp-versions }}
