name: Codeception Tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

env:
  TZ: UTC

jobs:
  test:

    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        operating-system: [ ubuntu-latest ]
        php-versions: [ '5.6', '7.0', '7.1', '7.2', '7.3' ]
        wp-versions: [ '4.9', '5.0', '5.1', '5.2', '5.3', '5.4', '5.5', '5.6' ]

    name: WP ${{ matrix.wp-versions }} | PHP ${{ matrix.php-versions }} | ${{ matrix.operating-system }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Shutdown Ubuntu MySQL
        run: sudo service mysql stop

      - name: Install MariaDB
        uses: getong/mariadb-action@v1.1
        with:
          character set server: 'utf8'
          collation server: 'utf8_general_ci'
          mariadb version: 'latest'
          mysql root password: 'root'
          mysql user: 'root'
          mysql password: 'root'

      - name: MariaDB Version
        run: mysql --version

      - name: Install and Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mysql, pdo, pdo_mysql, gd, imagick, mbstring, intl, zip, json, xdebug
          ini-values: post_max_size=256M
          tools: pecl
          coverage: true

      - name: Install Apache
        run: sudo apt-get install apache2 && sudo apt-get install libapache2-mod-php${{ matrix.php-versions }} && sudo a2enmod rewrite && sudo service apache2 restart

      - name: PHP Version
        run: php -v

      - name: PHP Extensions
        run: php -m

      - name: Validate Composer
        run: composer validate

      - name: Install Composer Dependencies
        run: composer install --prefer-dist --no-suggest --no-progress

      - name: Build WordPress ${{ matrix.wp-versions }}
        run: ./init ${{ matrix.wp-versions }}

      - name: Verify Environment
        run: cat ./.env.testing

      - name: Localhost is working?
        run: wget localhost && cat index.html

      - name: Prepare Selenium and Google Chrome
        run: |
          sudo mkdir -p /opt/tests
          sudo wget https://selenium-release.storage.googleapis.com/3.141/selenium-server-standalone-3.141.59.jar -O /opt/tests/selenium.jar
          sudo chmod +x /opt/tests/selenium.jar
          sudo wget https://chromedriver.storage.googleapis.com/87.0.4280.88/chromedriver_linux64.zip -O /opt/tests/chromedriver.zip
          sudo unzip /opt/tests/chromedriver.zip -d /opt/tests
          sudo chmod +x /opt/tests/chromedriver
          sudo java -Dwebdriver.chrome.driver=/opt/tests/chromedriver -jar /opt/tests/selenium.jar &

      - name: Run Codeception
        run: php ./vendor/bin/codecept run acceptance

      - name: Archive Tests Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: codeception-data
          path: tests/_output
