name: Package

on:
  push:
    branches:
      - main

jobs:
  package:

    runs-on: ubuntu-latest

    name: WordPress Plugin Package

    steps:
      - uses: actions/checkout@v2

      - name: Generate the Plugin Package
        run: ./package

      - name: Archive Package Artifact
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: tests/_data/plugin/wp-nox-login-required.zip
          if-no-files-found: error
          retention-days: 5
