name: PHP CS

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install composer dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Prepare Selenium
        run: |
          sudo mkdir -p /opt/tests
          sudo wget https://selenium-release.storage.googleapis.com/3.141/selenium-server-standalone-3.141.59.jar -O /opt/tests/selenium.jar
          sudo chmod +x /opt/tests/selenium.jar
          sudo wget https://chromedriver.storage.googleapis.com/88.0.4324.27/chromedriver_linux64.zip -O /opt/tests/chromedriver.zip
          sudo unzip /opt/tests/chromedriver.zip -d /opt/tests
          sudo chmod +x /opt/tests/chromedriver
          sudo java -Dwebdriver.chrome.driver=/opt/tests/chromedriver -jar /opt/tests/selenium.jar

      - name: Run phpcs in the project
        run: composer phpcs
